<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>loyout web</title>
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <main>
        <h2>Text Adventure</h2>

        <div class="container">

            <div class="box-console">
                <p><?=  $arrayAssociativo = $conteudo ?></p>
            </div>

            <form>

                <input type="text" name="comando" />
             
                <input type="submit" class="submit" />
            </form>

        </div>
    </main>
</body>

</html>